FROM mariadb:10.5.1

ENV MYSQL_USER=testuser \
    MYSQL_PASSWORD=password \
    MYSQL_ROOT_PASSWORD=password

# COPY my.cnf /etc/mysql/conf.d/my.cnf
# COPY world.sql /docker-entrypoint-initdb.d/world.sql